services:
 - docker

before_install:
 - echo "KUBERNAUT_TOKEN=${KUBERNAUT_TOKEN}" > env
 - echo "FORGE_ECR_KEY_ID=AKIAJ7QOAJNVBN4E66BA" >> env
 - echo "FORGE_ECR_SECRET_KEY=${FORGE_ECR_SECRET_KEY}" >> env
 - echo "DEPLOY_KEY_ID=AKIAIVJWBEJIYPFYB3FQ" >> env
 - echo "DEPLOY_KEY=${DEPLOY_KEY}" >> env

script:
 - ./dev.sh release
